name: Build 50 - ORE MacOS ARM64 Executable

on: workflow_dispatch
jobs:
  build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3
    - name: Install Eigen
      run: |
        brew install eigen
    - name: Install Boost
      run: |
        curl -O -L https://boostorg.jfrog.io/artifactory/main/release/1.80.0/source/boost_1_80_0.tar.gz
        tar xfz boost_1_80_0.tar.gz
        cd boost_1_80_0
        ./bootstrap.sh
        ./b2 architecture=arm address-model=64 -s NO_LZMA=1 -s NO_ZSTD=1 abi=aapcs install
    - name: Build ORE
      run: |
        pwd
        tar xfz ore.tgz
        #cp exchangerate.hpp ore/QuantLib/ql
        #tar xfz oreswig.tgz
        #cp setup.py oreswig/OREAnalytics-SWIG/Python/setup.py
        #cp oreanalytics-config.macos
        cd ore
        mkdir build
        cd build
        cmake -DCMAKE_OSX_ARCHITECTURES=arm64 -DORE_USE_ZLIB=ON -DORE_BUILD_DOC=OFF -DORE_BUILD_EXAMPLES=OFF -DORE_BUILD_TESTS=OFF -DORE_BUILD_APP=ON -DQL_BUILD_BENCHMARK=OFF -DQL_BUILD_EXAMPLES=OFF -DQL_BUILD_TEST_SUITE=OFF -DQL_ENABLE_SESSIONS=ON -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . -j4
        cmake --install .
    - name: Find File Path
      run: |
        file_path=$(find . -name 'ore.exe')
        echo "Found file at path: $file_path"
    - name: Save executables as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ore-exe-macos-arm64
        path: "$file_path"
